### PR TITLE
LexiconToggle component

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Can't we reuse https://github.com/metal/metal-toggler?

**Comment by jbalsas** [comment]
Hey @eduardolundgren, that's probably my fault. I didn't remember it when I did the base examples, so I just followed the old naming, but makes sense that we could reuse it.

@Robert-Frampton could you check if that's equivalent? If so, could you also update the other instances where we use this?

Thanks for pointing this out Eduardo!

**Comment by Robert-Frampton** [comment]
Hey @eduardolundgren 

The lexicon-toggler actually corresponds to the [this component](http://liferay.github.io/lexicon/content/toggles/) which is a type of checkbox. The metal-toggler on the other hand is more like the AUI toggler.

**Comment by eduardolundgren** [comment]
Got it. Thanks.

**Comment by Robert-Frampton** [comment]
Resent at https://github.com/liferay-lexicon/lexicon-switch/pull/2

**Comment by eduardolundgren** [comment]
I would still call it Switcher for consistence with Metal components and then we can rename both together if that's the case.

**Comment by Robert-Frampton** [comment]
I think we should definitely go with `switch`. It sounds a lot more natural. can we just merge this the way it is and update metal-switcher today?

**Comment by natecavanaugh** [comment]
@eduardolundgren I think this should be `switch`, and that the Metal component is named wrong.

Switch is a noun, and switcher as a word doesn't exist, so I think we should fix the metal one. If you don't want to rename the metal one, that's fine, but renaming it afterwards (which will probably never happen), will end up causing more breakages.

I think we should be more careful with how we name things to prevent issues like this.

**Pull request closed without merging**
